#include <iostream>
#include <fstream>

#include "CS229Writer.h"

void CS229Writer::writeFile(AudioFile &file, string filename) {
	// create the file, then redirect to writeFile
	ofstream output;
	output.open(filename);
	writeFile(file, output);
	output.close();
}

void CS229Writer::writeFile(AudioFile &file, ostream &os) {
	// print out the header
	os << "CS229" << endl;
	os << endl;
	os << "# Generated by 'CS229Writer'" << endl;
	os << endl;
	os << "Channels " << file.get_num_channels() << endl;
	os << "BitRes " << file.get_bit_res() << endl;
	os << "SampleRate " << file.get_sample_rate() << endl;
	os << "Samples " << file.get_num_samples() << endl;
	os << endl;
	os << "StartData" << endl;
	os << endl;

	// now print out all of the data
	for (size_t i = 0; i < file.get_num_samples(); i++) {
		for (size_t c = 0; c < file.get_num_channels(); c++) {
			os << file[c][i] << " ";
		}

		os << endl;
	}
}
